# Generated by Django 5.2.7 on 2025-10-14 20:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('identificacion', models.CharField(max_length=50, unique=True, verbose_name='Número de Identificación')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CodigoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comida', models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo'), ('REFRIGERIO', 'Refrigerio')], max_length=20, verbose_name='Tipo de Comida')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código QR')),
                ('usado', models.BooleanField(default=False, verbose_name='Usado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_uso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Uso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_qr', to='event_management.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Código QR',
                'verbose_name_plural': 'Códigos QR',
                'ordering': ['estudiante', 'tipo_comida'],
                'unique_together': {('estudiante', 'tipo_comida')},
            },
        ),
    ]
