# Generated by Django 5.2.7 on 2025-10-21 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=200, verbose_name='Nombre Completo')),
                ('identificacion', models.CharField(db_column='identificacion', max_length=50, verbose_name='Identificación')),
                ('email', models.EmailField(db_column='email', max_length=254, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'db_table': 'visitantes',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='codigoqr',
            options={'ordering': ['visitante_nombre', 'tipo_comida'], 'verbose_name': 'Código QR', 'verbose_name_plural': 'Códigos QR'},
        ),
        migrations.AlterUniqueTogether(
            name='codigoqr',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='codigoqr',
            name='visitante_email',
            field=models.EmailField(default='noemail@example.com', max_length=254, verbose_name='Email Visitante'),
        ),
        migrations.AddField(
            model_name='codigoqr',
            name='visitante_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Visitante'),
        ),
        migrations.AddField(
            model_name='codigoqr',
            name='visitante_identificacion',
            field=models.CharField(default='', max_length=50, verbose_name='Identificación Visitante'),
        ),
        migrations.AddField(
            model_name='codigoqr',
            name='visitante_nombre',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre Visitante'),
        ),
        migrations.AlterField(
            model_name='codigoqr',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos_qr', to='event_management.estudiante', verbose_name='Estudiante'),
        ),
        migrations.AlterUniqueTogether(
            name='codigoqr',
            unique_together={('visitante_email', 'tipo_comida')},
        ),
    ]
