# Generated by Django 5.2.7 on 2025-10-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_visitante_alter_codigoqr_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoqr',
            name='visitante_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Visitante (Documento)'),
        ),
    ]
